fun main(){
    print("enter student enroll.:")
    var enro = readLine()
    print("student name:")
    var name = readLine()
    print("Student Branch:")
    var Branch = readLine()
    print("Student Class:")
    var Class = readLine()
    print("Student Batch:")
    var Batch = readLine()
    print("Student College Name:")
    var college = readLine()
    print("student uni:")
    var uni = readLine()
    print("age:")
    var age = readLine()

    println("Student Information:")
    println("enrollment no:${enro}")
    println("Name: ${name}")
    println("Branch:${Branch}")
    println("Class:${Class}")
    println("Batch:${Batch}")
    println("College:${college}")
    println("University:${uni}")
    println("Age:${age}")
}